#cloud-config
package_upgrade: true
packages:
  - libfontconfig1

write_files:
  - path: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

  - path: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'Web-servers-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['web-server-0:80','web-server-1:80']

        - job_name: 'Load-balancer-metrics'
          scrape_interval: 5s
          static_configs: 
            - targets: ['load-balancer-server-0:80']

  - path: /etc/grafana/provisioning/datasources/datasource.yaml
    content: |
      apiVersion: 1

      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          jsonData:
            httpMethod: POST

runcmd:
  - useradd --no-create-home --shell /bin/false prometheus
  - wget https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-amd64.tar.gz
  - wget https://dl.grafana.com/oss/release/grafana_8.4.4_amd64.deb
  - dpkg -i grafana_*_amd64.deb
  - tar xvfz prometheus-*.tar.gz
  - mkdir /var/lib/prometheus
  - chown -R prometheus:prometheus /var/lib/prometheus/
  - cp prometheus-*/prometheus /usr/local/bin/
  - cp prometheus-*/promtool /usr/local/bin/
  - chown prometheus:prometheus /usr/local/bin/promtool
  - chown prometheus:prometheus /usr/local/bin/prometheus
  - cp -r  prometheus-*/console_libraries /etc/prometheus/
  - cp -r  prometheus-*/consoles /etc/prometheus/
  - chown -R prometheus:prometheus /etc/prometheus/console_libraries
  - chown -R prometheus:prometheus /etc/prometheus/consoles
  - systemctl start prometheus grafana-server
  - systemctl enable prometheus grafana-server

output: { all: "| tee -a /var/log/nginx-demo.log" }