name: ansible_lint

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'ansible_lab/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ansible-lint:
    name: 'ansible-lint'
    runs-on: ubuntu-latest
    env:
      work_dir: "./ansible_lab"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Run ansible-lint'
        uses: ansible-community/ansible-lint-action@v6
        with:
          path: 'playbooks/'
